export const FETCH_WALLET_DATA = 'FETCH_WALLET_DATA';
export const FETCH_WALLET_SUCCESS = 'FETCH_WALLET_SUCCESS';
export const FETCH_WALLET_FAILURE = 'FETCH_USER_FAILURE';
export const ADD_RELEASE_WALLET = 'ADD_RELEASE_WALLET';
